
export const REQUESTING = "REQUESTING";
export const REQUESTING_DETAIL = "REQUESTING_DETAIL";
export const ALL_ACTIVOS_USUARIO = "ALL_ACTIVOS_USUARIO";
export const ALL_ACTIVOS_USUARIO_FAIL = 'ALL_ACTIVOS_USUARIO_FAIL'

export const ALL_ACTAS_USUARIO = 'ALL_ACTAS_USUARIO'
export const ACTA_USUARIO = 'ACTA_USUARIO'

export const NEW_ACTA = 'NEW_ACTA'
export const CREATE_ACTA = 'CREATE_ACTA'
export const UPDATE_ACTA = 'UPDATE_ACTA'
export const CREATE_DETALLE_ACTA = 'CREATE_DETALLE_ACTA'
export const DELETE_DETALLE_ACTA = 'DELETE_DETALLE_ACTA' 
export const AREA_DETALLE_ACTA = 'AREA_DETALLE_ACTA'
export const APRUEBA_ACTA = 'APRUEBA_ACTA'
export const REQUESTING_APRUEBA = 'REQUESTING_APRUEBA'
export const APRUEBA_SUCCESS = 'APRUEBA_SUCCESS'


export const ALL_ACTAS_CUSTODIO_ADMINISTRATIVO = 'ALL_ACTAS_CUSTODIO_ADMINISTRATIVO'





// export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST";
// export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
// export const CREATE_ORDER_FAIL = "CREATE_ORDER_FAIL";

// export const MY_ORDERS_REQUEST = "MY_ORDERS_REQUEST";
// export const MY_ORDERS_SUCCESS = "MY_ORDERS_SUCCESS";
// export const MY_ORDERS_FAIL = "MY_ORDERS_FAIL";


// export const UPDATE_ORDER_REQUEST = "UPDATE_ORDER_REQUEST";
// export const UPDATE_ORDER_SUCCESS = "UPDATE_ORDER_SUCCESS";
// export const UPDATE_ORDER_RESET = "UPDATE_ORDER_RESET";
// export const UPDATE_ORDER_FAIL = "UPDATE_ORDER_FAIL";

// export const DELETE_ORDER_REQUEST = "DELETE_ORDER_REQUEST";
// export const DELETE_ORDER_SUCCESS = "DELETE_ORDER_SUCCESS";
// export const DELETE_ORDER_RESET = "DELETE_ORDER_RESET";
// export const DELETE_ORDER_FAIL = "DELETE_ORDER_FAIL";

// export const ORDER_DETAILS_REQUEST = "ORDER_DETAILS_REQUEST";
// export const ORDER_DETAILS_SUCCESS = "ORDER_DETAILS_SUCCESS";
// export const ORDER_DETAILS_FAIL = "ORDER_DETAILS_FAIL";

// export const CLEAR_ERRORS = "CLEAR_ERRORS";